### ISSUE TITLE
Test Pr2

### ISSUE THREAD

**Issue by sheredia** [sheredia/TestZhenbot#17]

**Comment by sheredia** [comment]
:accept: test-pr2

**Comment by sheredia** [comment]
![](https://cdn3.vox-cdn.com/thumbor/9Ke1QsWFXy7kfbKGW7Qt2CrorOo=/1600x0/filters:no_upscale()/cdn0.vox-cdn.com/uploads/chorus_asset/file/3769944/robotgif_2.0.gif) <br/>Zhenbot™ was unable to create Pull Request for test-pr2. Sorry about that :person_frowning:. Exception: System.AggregateException: One or more errors occurred. ---> Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__e`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GithubHooks.Controllers.HooksController.PullAndMerge(String branchName, Int32 issueNumber, String issueTitle, ApiConnection apiConnection, GitHubClient github, JsonSerializerSettings settings) in c:\Users\sara5767\Github\Github-Acceptance-Hook\GithubHooks\Controllers\HooksController.cs:line 82
---> (Inner Exception #0) Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__e`1.MoveNext()<---
