### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by sheredia** [sheredia/TestZhenbot#3]

**Comment by sheredia** [comment]
:accept: another-change

**Comment by sheredia** [comment]
Zhenbot™ was unable to create Pull Request for another-change. Sorry about that :person_frowning:. Exception: System.AggregateException: One or more errors occurred. ---> Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__e`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GithubHooks.Controllers.HooksController.PullAndMerge(String branchName, Int32 issueNumber, String issueTitle, ApiConnection apiConnection, GitHubClient github, JsonSerializerSettings settings) in c:\Users\sara5767\Github\Github-Acceptance-Hook\GithubHooks\Controllers\HooksController.cs:line 77
---> (Inner Exception #0) Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__e`1.MoveNext()<---

**Comment by sheredia** [comment]
:accept: another-branch

**Comment by sheredia** [comment]
Pulled (#4) and deleted another-branch :ok_woman:. Zhenbot™ signing off.
